git config --global alias.st 'status -sb' 
git config --global alias.co 'checkout' 
git config --global alias.su 'submodule update --init --recursive' 
git config --global alias.b 'checkout -b' 
git config --global alias.cmu 'commit -m "update"' 
git config --global alias.cm 'commit -m'
git config --global alias.ai 'add -i'
git config --global alias.who 'add shortlog -s -n --all'